FDC3 2.0 Adds/Edits/Deletes
morganstanley/fdc3-dotnet pull request #8
Opened 2023-01-31 20:07 UTC by bingenito

2023-02-01 00:34 UTC, psmulovics commented on src/Fdc3/Context/Currency.cs
> +        public string? CURRENCY_ISOCODE { get; set; }
Was this fixed in the end?

2023-02-01 00:35 UTC, psmulovics commented on src/Fdc3/IIcon.cs
> +        /// The icon dimensions</height>'
</height> ?

2023-02-01 00:36 UTC, psmulovics commented on src/Fdc3/IImage.cs
> +        /// The icon dimensions</height>'
`</height>` ?

2023-02-01 00:37 UTC, psmulovics commented on src/Fdc3/IIntentResult.cs
> +    public interface IIntentResult {
Do we need to add a `#pragma` here?

2023-02-01 00:38 UTC, psmulovics requested changes
Left a few code smelly comments

2023-02-01 11:15 UTC, bingenito commented on src/Fdc3/Context/Currency.cs
> +        public string? CURRENCY_ISOCODE { get; set; }
That was on valuation, and yes - https://github.com/finos/FDC3/issues/833

2023-02-01 11:23 UTC, bingenito commented on src/Fdc3/IIcon.cs
> +        /// The icon dimensions</height>'
Copy paste and autocorrect thinking it was html or xml in the comments really butchered it.

2023-02-01 11:28 UTC, psmulovics approved these changes

2023-02-01 12:10 UTC, merged

2023-02-02 20:37 UTC, bingenito commented
Fixes #4